name: Tests
on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
  test:
    name: test
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.10", "3.11" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run pytest
      run: |
        poetry run pytest .
